version: "3.8"
services:
  payment-api:
    build: .
    container_name: remittance-payout-api
    env_file:
      - .env
    ports:
      - 8080:8080
    environment:
      SEERBIT_CLIENT_ID: ${CLIENT_ID}
      SEERBIT_SECRET: ${CLIENT_SECRET}

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8081:8080"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json

